### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by DennieMello** [fivethree-team/nestjs-prisma-starter#439]
If you create more than 10 modules in the providers of which "PrismaService" is located, the error "Possible EventEmitter memory leak detected." The more modules are added, the more error instances are displayed. Is there a way to fix this?

![Снимок экрана 2021-04-10 в 07 33 29](https://user-images.githubusercontent.com/39631512/114258464-49c72500-99cf-11eb-963c-0cbbf3ef380b.jpg)
![Снимок экрана 2021-04-10 в 07 32 27](https://user-images.githubusercontent.com/39631512/114258465-4b90e880-99cf-11eb-9aae-9606de70ce1c.jpg)

**Error**
`(node:15126) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at process.addListener (events.js:406:10)
    at process.once (events.js:437:8)
    at hookProcess (/Users/Rikka/iMac/Projects/apps/nestGQLError2/node_modules/@prisma/client/runtime/index.js:27586:13)
    at initHooks (/Users/Rikka/iMac/Projects/apps/nestGQLError2/node_modules/@prisma/client/runtime/index.js:27609:9)
    at new NodeEngine (/Users/Rikka/iMac/Projects/apps/nestGQLError2/node_modules/@prisma/client/runtime/index.js:26911:7)
    at PrismaService.getEngine (/Users/Rikka/iMac/Projects/apps/nestGQLError2/node_modules/@prisma/client/runtime/index.js:34057:16)
    at new NewPrismaClient (/Users/Rikka/iMac/Projects/apps/nestGQLError2/node_modules/@prisma/client/runtime/index.js:34030:29)
    at new PrismaService (/Users/Rikka/iMac/Projects/apps/nestGQLError2/dist/services/prisma.service.js:17:9)
    at Injector.instantiateClass (/Users/Rikka/iMac/Projects/apps/nestGQLError2/node_modules/@nestjs/core/injector/injector.js:286:19)`

**Comment by yassinebridi** [comment]
This is probably not this repo's issue, but i would love to know why this happens.

**Comment by DennieMello** [comment]
I solved the problem by creating a module for prisma and importing modules, instead of adding services.

**Comment by yassinebridi** [comment]
I think this has been fixed with the latest prisma release:
https://github.com/prisma/prisma/issues/6584#issuecomment-820471095

**Comment by marcjulian** [comment]
I am closing this issue for now. Report back if the issue appears again or report an issue directly with prisma.
